spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 457903ba-ad4e-4a53-9f39-715449ec9197
            client-secret: nz48Q~ljX~1T~YYFP8Oz3.IQ0VYTgqBlCOOyNar5
            scope: openid, profile, email, User.Read
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/azure"
            authorization-uri: https://login.microsoftonline.com/*/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/*/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            jwk-set-uri: https://login.microsoftonline.com/*/discovery/v2.0/keys
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/*/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/*/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
